// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINHRYZ5aublOTlSBWsOIYevHjbLDSjGw',
    appId: '1:475549178638:web:e6d41d1499a32a84b1d55f',
    messagingSenderId: '475549178638',
    projectId: 'nowochat-2dc13',
    authDomain: 'nowochat-2dc13.firebaseapp.com',
    storageBucket: 'nowochat-2dc13.appspot.com',
    measurementId: 'G-M9FB13SLRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANgo54BOwWA-MVlSMvKZWFW0a5FxnFS-8',
    appId: '1:475549178638:android:12524a6a1fbc6bcab1d55f',
    messagingSenderId: '475549178638',
    projectId: 'nowochat-2dc13',
    storageBucket: 'nowochat-2dc13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCym2QnkvpdA4LQ-wPQdIzDNUF2AIx7B2c',
    appId: '1:104570725171:android:daf15260471a4f2c40d446',
    messagingSenderId: '104570725171',
    projectId: 'dubai-tourist',
    storageBucket: 'nowochat-2dc13.appspot.com',
    androidClientId:
        '475549178638-4n2hgqgn6mkgnjma33kv8lceb7s8g3vo.apps.googleusercontent.com',
    iosClientId:
        '104570725171-mj077noqeq8fer2ahph5du3gn4nvblkt.apps.googleusercontent.com',
    iosBundleId: 'com.tourist.vivah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2q1WwI7KVpbS5KI06a18VrkFfQET0R78',
    appId: '1:475549178638:ios:73c4768b4514a675b1d55f',
    messagingSenderId: '475549178638',
    projectId: 'nowochat-2dc13',
    storageBucket: 'nowochat-2dc13.appspot.com',
    androidClientId:
        '475549178638-4n2hgqgn6mkgnjma33kv8lceb7s8g3vo.apps.googleusercontent.com',
    iosClientId:
        '475549178638-o70s8hj7v0gnm7itl47e49quudem8mjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nowochat',
  );
}
